version: "3"
services:
  backend:
    build:
      context: backend
      dockerfile: backend/Dockerfile
      args:
        - app_port=${APP_PORT}
    ports:
      - "8000:${APP_PORT}"
    volumes:
      - /backend:/app
    env_file: backend/.env
    tty: true
    depends_on:
      - redis
  redis:
    image: redis/redis-stack:latest
    ports:
      - "8001:6379"
      - "8002:8001"
  frontend:
    build:
      context: frontend
      dockerfile: frontend/Dockerfile
      args:
        - app_port=${REACT_APP_PORT}
    ports:
      - "8003:${REACT_APP_PORT}"
    volumes:
      - /frontend:/app
    env_file: frontend/.env
    tty: true
    depends_on:
      - backend
