version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - app_port=${APP_PORT}
    ports:
      - "8000:${APP_PORT}"
    volumes:
      - /backend:/app
    env_file: backend/.env
    tty: true
    depends_on:
      - redis
  redis:
    image: redis/redis-stack:latest
    ports:
      - "8001:6379"
      - "8002:8001"
